#development:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: DRPdev
#  pool: 5
#  username: root
#  password: bananas
#  shost: localhost
#test:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: DRPtest
#  pool: 5
#  username: root
#  password: bananas
#  shost: localhost
#production:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: DRP
#  pool: 5
#  username: root
#  password: bananas
#  shost: localhost

development:
  adapter: postgis
  schema_search_path: public
  encoding: unicode
  database: DRP4
  host: localhost
  pool: 5
  username: postgres
  password: