# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef85e0271d53a478db6a8ddd49a9eba3f7496cfe7097b43730c29197564a93bf60188fbfaabcd26ebcc51951fe2f8ae5544fdd81cb06c00bdbcd499ad173efec

test:
  secret_key_base: 403c40566873575980a73225bf155828c3313dc010f791c47fe08899e9eceaec58b8e1e1edeba64abe2bb63f72608da849a20c1b2646722389f8d465b21fa769

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
